version: '3.8'

services:

  cpo:
    build:
      context: ./src
      target: demo
      args:
        DOCKER_USER: ${DOCKER_USER:-1000}
    user: ${DOCKER_USER:-1000}
    image: "ocpi:demo"
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app
